# playbook for install elasticsearch

- name: "Загрузка elastic"
  get_url:
    url=https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearc>      url=https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.17.9-amd64.deb
    dest=/home/denis

- name: "Установка elastic"
  command:
    dpkg -i /home/denis/elasticsearch-7.17.9-amd64.deb

- name: "Systemctl daemon reload"
  systemd:
    daemon_reload: true

- name: "Стартуем elastic"
  service:
    name=elasticsearch
    enabled=yes
    state=started

- name: "Меняем файл /etc/elasticsearch/elasticsearch.yml"
  copy:
    src=/home/denis/ansible/elastic/elasticsearch.yml
    dest=/etc/elasticsearch/elasticsearch.yml
    mode=0644
    owner=root
    group=elasticsearch

- name: "Restart elastic"
  systemd:
    name=elasticsearch
    state=restarted

