webservers:
  children:
    server1:
      hosts:
        server1.ru-central1.internal:
          port: 22
          ansible_ssh_user: denis
    server2:
      hosts:
        server2.ru-central1.internal:
          port: 22
          ansible_ssh_user: denis
zabbix_server:
      hosts:
        zabbix-server.ru-central1.internal:
          port: 22
          ansible_ssh_user: denis
elastic:
      hosts:
        elastic.ru-central1.internal:
          port: 22
          ansible_ssh_user: denis
kibana:
      hosts:
        kibana.ru-central1.internal:
          port: 22
          ansible_ssh_user: denis
